# Generated by Django 4.1.1 on 2022-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('prod_num', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('text_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('serial_num', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
